branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.1
env:
  - CODECLIMATE_REPO_TOKEN=0b58d4e91bfac6ed6e48b31606f6792598a3a59c27bded19d58ef8406c09f57c
cache:
  - bundler
  - apt
bundler_args: --binstubs --retry=5
before_script:
  - unset RAILS_ENV
  - unset RACK_ENV
  - bundle exec rake db:test_create
script:
  - bundle exec rake test
addons:
  code_climate:
    repo_token: 0b58d4e91bfac6ed6e48b31606f6792598a3a59c27bded19d58ef8406c09f57c
